version: '3.4'
services:
  idchain.dnp.dappnode.eth:
    image: 'idchain.dnp.dappnode.eth:0.0.1'
    build: ./build
    volumes:
      - 'idchain:/idchain'
    environment:
      - 'EXTRA_OPTS=--rpcapi eth,net,web3,txpool'
      - SYNCMODE
    ports:
      - '30303'
      - 30303/udp
      - 30304/udp
    restart: always
volumes:
  idchain: {}
